In [2]:
import pandas as pd
import datetime as dt

In [3]:
# Create the DataFrame
dates = pd.date_range(start='04/07/2022', periods=30, freq='D')
rpt = pd.DataFrame(columns=['Trading', 'Hold', '3X', 'Staked', 'Total'], index=dates)

In [4]:
#format datetime to M/D/Y
rpt.index = rpt.index.strftime('%m/%d/%Y')

In [5]:
# empty dataframe
rpt.head(5)

           Trading Hold   3X Staked Total
04/07/2022     NaN  NaN  NaN    NaN   NaN
04/08/2022     NaN  NaN  NaN    NaN   NaN
04/09/2022     NaN  NaN  NaN    NaN   NaN
04/10/2022     NaN  NaN  NaN    NaN   NaN
04/11/2022     NaN  NaN  NaN    NaN   NaN

In [6]:
#append
rpt.iloc[0] = [52.765, 74.915, 43.862 , 71.543, 243.812]
rpt.iloc[1] = [ 46, 112, 112, 68.656, 226.775]

In [7]:
rpt

           Trading    Hold      3X  Staked    Total
04/07/2022  52.765  74.915  43.862  71.543  243.812
04/08/2022      46     112     112  68.656  226.775
04/09/2022     NaN     NaN     NaN     NaN      NaN
04/10/2022     NaN     NaN     NaN     NaN      NaN
04/11/2022     NaN     NaN     NaN     NaN      NaN
04/12/2022     NaN     NaN     NaN     NaN      NaN
04/13/2022     NaN     NaN     NaN     NaN      NaN
04/14/2022     NaN     NaN     NaN     NaN      NaN
04/15/2022     NaN     NaN     NaN     NaN      NaN
04/16/2022     NaN     NaN     NaN     NaN      NaN
04/17/2022     NaN     NaN     NaN     NaN      NaN
04/18/2022     NaN     NaN     NaN     NaN      NaN
04/19/2022     NaN     NaN     NaN     NaN      NaN
04/20/2022     NaN     NaN     NaN     NaN      NaN
04/21/2022     NaN     NaN     NaN     NaN      NaN
04/22/2022     NaN     NaN     NaN     NaN      NaN
04/23/2022     NaN     NaN     NaN     NaN      NaN
04/24/2022     NaN     NaN     NaN     NaN      NaN
04/25/2022     NaN     NaN     NaN     NaN      NaN
04/26/2022     NaN     NaN     NaN     NaN      NaN
04/27/2022     NaN     NaN     NaN     NaN      NaN
04/28/2022     NaN     NaN     NaN     NaN      NaN
04/29/2022     NaN     NaN     NaN     NaN      NaN
04/30/2022     NaN     NaN     NaN     NaN      NaN
05/01/2022     NaN     NaN     NaN     NaN      NaN
05/02/2022     NaN     NaN     NaN     NaN      NaN
05/03/2022     NaN     NaN     NaN     NaN      NaN
05/04/2022     NaN     NaN     NaN     NaN      NaN
05/05/2022     NaN     NaN     NaN     NaN      NaN
05/06/2022     NaN     NaN     NaN     NaN      NaN